mutation CreatePublicMovieList(
    $name: String!
    $description: String!
) @auth(level: USER) {
  movieList_insert(
    data: {
      name: $name
      description: $description
      isPublic: true
      userId_expr: "auth.uid"
      createdAt_expr: "request.time"
      updatedAt_expr: "request.time"
    }
  ) {
    id
  }
}

query GetMyPublicMovieLists @auth(level: USER) {
  movieLists(where: {userId: {eq_expr: "auth.uid"}, isPublic: {eq: true}}) {
    id
    name
    description
    createdAt
    updatedAt
  }
}

mutation AddMovieToList(
    $movieListId: UUID!
    $movieId: UUID!
    $position: Int!
    $note: String
) @auth(level: USER) {
  movieListEntry_insert(
    data: {
      movieListId: $movieListId
      movieId: $movieId
      position: $position
      note: $note
    }
  ) {
    id
  }
}

query GetMoviesInList($movieListId: UUID!) @auth(level: USER) {
  movieListEntries(where: {movieListId: {eq: $movieListId}}) {
    id
    movie {
      id
      title
      year
      summary
      genres
      runtimeMinutes
    }
    position
    note
  }
}